@extends('admin.layout')

@section('admin-title') Breeding Roller @endsection

@section('admin-content')
{!! breadcrumbs(['Admin Panel' => 'admin', 'Genetics' => 'admin/genetics/genes', 'Breeding Roller' => 'admin/genetics/roller']) !!}

<h1>Breeding Roller</h1>
<p><strong>Traits are not heritable or set automatically.</strong> This is just for genome creation via inheritance.</p>

<hr>

{!! Form::open(['url' => 'admin/genetics/roll-litter', 'files' => true ]) !!}

<div class="row align-items-end">
    @for ($i = 0; $i < 2; $i++)
        <div class="col-md-6">
            <div class="card mb-3 mb-md-0">
                <div class="card-header">
                    <h5 class="mb-0 text-center">{{ $i == 0 ? "Matrilineage" : "Patrilineage"}}</h5>
                </div>
                <div class="card-body">
                    {!! Form::select('parents[]', [0 => "Select Character"] + $characters, 0, ['id' => $i==0 ? "mother" : "father", 'class' => 'form-control parent-select']) !!}
                </div>
                <ul class="list-group list-group-flush genomes"></ul>
            </div>
        </div>
    @endfor
</div>

<hr>
<div class="row justify-content-center breeding-result">
    <div class="col-12 col-md-6">
        <h3>Roller Settings</h3>
        <div class="row justify-content-center no-gutters">
            @php
                $col = "col-12 col-sm-6 col-md-12 col-xl-6 ";
                $left = "pr-sm-2 pr-md-0 pr-xl-2";
                $right = "pl-sm-2 pl-md-0 pl-xl-2";
            @endphp
            <div class="{{ $col.$left }}">
                {!! Form::label('min_offspring', "Litter Min & Max Size") !!}
                <div class="input-group mb-3">
                    {!! Form::number('min_offspring', old('min_offspring', 0), ['class' => 'form-control', 'id' => "size_min", 'min' => 0]) !!}
                    {!! Form::number('max_offspring', old('max_offspring', 1), ['class' => 'form-control', 'id' => "size_max", 'min' => 1]) !!}
                </div>
            </div>
            <div class="{{ $col.$right }}">
                {!! Form::label('twin_chance', "Twin % Chance") !!} & {!! Form::label('twin_depth', "Max Depth") !!}
                <div class="input-group mb-3">
                    {!! Form::number('twin_chance', old('twin_chance', 0), ['class' => 'form-control', 'id' => "twin_chance", 'min' => 0, 'max' => 100]) !!}
                    {!! Form::number('twin_depth', old('twin_depth', 1), ['class' => 'form-control', 'id' => "twin_depth", 'min' => 1]) !!}
                </div>
            </div>
            <div class="{{ $col.$left }}">
                {!! Form::label('chimera_chance', "Chimerism %") !!} & {!! Form::label('chimera_depth', "Total Maximum Genomes") !!}
                <div class="input-group mb-3">
                    {!! Form::number('chimera_chance', old('chimera_chance', 0), ['class' => 'form-control', 'id' => "chimera_chance", 'min' => 0, 'max' => 100]) !!}
                    {!! Form::number('chimera_depth', old('chimera_depth', 2), ['class' => 'form-control', 'id' => "chimera_depth", 'min' => 1]) !!}
                </div>
            </div>
            <div class="{{ $col.$right }} d-flex align-items-end">
                <div class="form-group w-100 mb-3">
                    {!! Form::label('litter_limit', "True Maximum Litter Size") . add_help("Since twins can go over the normal size limit, this will set a HARD LIMIT to how many offspring can result from a pair.") !!}
                    {!! Form::number('litter_limit', old('litter_limit', 10), ['class' => 'form-control', 'id' => "litter_limit", 'min' => 1]) !!}
                </div>
            </div>
            <div class="col-6 mt-1 text-center">
                <a href="#" class="btn btn-success preview-breeding">Roller Test <i class="fas fa-dice ml-1"></i></a>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="card mb-md-0">
            <div class="card-header">
                <h5 class="mb-0 text-center">Roller Preview</h5>
            </div>
            <ul class="list-group list-group-flush child-genomes"></ul>
        </div>
    </div>
</div>
<hr>

<h3>Myo Settings</h3>
<p class="alert alert-info">Settings input here will be applied to <strong>every single myo</strong> generated by the roller. Only the genomes and the offspring number placed in the myo name will be unique. <strong>Traits, as well as any variation in species or rarity, will need to be manually set after the myos are generated.</strong></p>

<div class="row">
    <div class="col-12 col-sm-6">
        <div class="form-group">
            {!! Form::label('name', "Litter Name") . add_help("This will be the name of every MYO generated. The number of the offspring within the litter will be added to the end of the name. (Any spaces at the end of the name will be ignored.)") !!}
            {!! Form::text('name', old('name'), ["class" => "form-control", "placeholder" => "Litter Name #"]) !!}
        </div>
        <div class="form-group">
            {!! Form::label('user_id', "Litter Recipient") . add_help("The user that recieves the generated myos.") !!}
            {!! Form::select('user_id', $userOptions, old('user_id', 1), ["class" => "form-control"]) !!}
        </div>
        <div class="form-group">
            @php $dVis = Settings::get('genome_default_visibility'); @endphp
            {!! Form::label('genome_visibility', 'Genome Visibility') . add_help("The visibility level of all these children's genomes. (The default site setting for genome visibility is ". ($dVis < 1 ? "Completely Hidden" : ($dVis == 1 ? "Half-Hidden" : "Fully Visible")) .".)") !!}
            {!! Form::select('genome_visibility', [0 => "Completely Hidden", 1 => "Half-Hidden", 2 => "Completely Visible"], old('genome_visibility', $dVis), ['class' => "form-control"]) !!}
        </div>
    </div>
    <div class="col-12 col-sm-6">
        <div class="form-group">
            {!! Form::label('species_id', 'Species (Optional)') . add_help('This will lock the slot into a particular species. Leave it blank if you would like to give the user a choice.') !!}
            {!! Form::select('species_id', $speciesOptions, old('species_id'), ['class' => 'form-control', 'id' => 'species']) !!}
        </div>
        <div class="form-group" id="subtypes">
            {!! Form::label('subtype_id', 'Subtype (Optional)') . add_help('This will lock the slot into a particular subtype. Leave it blank if you would like to give the user a choice, or not select a subtype. The subtype must match the species selected above, and if no species is specified, the subtype will not be applied.') !!}
            {!! Form::select('subtype_id', $subtypes, old('subtype_id'), ['class' => 'form-control disabled', 'id' => 'subtype']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('rarity_id', 'Rarity (Optional)') . add_help('This will lock the slot into a particular rarity. Leave it blank if you would like to give the user more choices.') !!}
            {!! Form::select('rarity_id', $rarities, old('rarity_id'), ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-12">
        {!! Form::label("Visibility & Transfer Settings (Optional)") !!}
        <div class="d-flex flex-wrap">
            <div class="form-group-inline mr-3 mb-2">
                {!! Form::checkbox('is_visible', 1, old('is_visible'), ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'data-on' => "Visible", 'data-off' => "Not Visible"]) !!}
            </div>
            <div class="form-group-inline mr-3 mb-2">
                {!! Form::checkbox('is_giftable', 1, old('is_giftable'), ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'data-on' => "Giftable", 'data-off' => "Not Giftable"]) !!}
            </div>
            <div class="form-group-inline mr-3 mb-2">
                {!! Form::checkbox('is_tradeable', 1, old('is_tradeable'), ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'data-on' => "Tradeable", 'data-off' => "Not Tradeable"]) !!}
            </div>
            <div class="form-group-inline mr-3 mb-2">
                {!! Form::checkbox('is_sellable', 1, old('is_sellable'), ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'data-on' => "Resellable", 'data-off' => "Not Resellable", 'id' => "resellable"]) !!}
            </div>
            <div class="form-group-inline mr-3 mb-2" id="resellOptions">
                {!! Form::text('sale_value', old('sale_value'), ['class' => 'form-control', 'placeholder' => 'Resale Value']) !!}
            </div>
            <div class="form-group-inline mb-3">
                {!! Form::text('transferrable_at', old('transferrable_at'), ['class' => 'form-control', 'id' => 'datepicker', 'placeholder' => "Transfer Cooldown"]) !!}
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::label('Description (Optional)') . add_help('This section is for making additional notes about the MYO slot. If there are restrictions for the character that can be created by this slot that cannot be expressed with the options below, use this section to describe them.') !!}
    {!! Form::textarea('description', old('description'), ['class' => 'form-control wysiwyg']) !!}
</div>

<hr>
<h3>Image Upload</h3>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">
            Upload Image (Optional)
            {!! add_help('This is a cover image for the MYO slot. If left blank, a default image will be used.') !!}
        </span>
    </div>
    <div class="custom-file">
        {!! Form::file('image', ['id' => 'mainImage', 'class' => "custom-file-input"]) !!}
        {!! Form::label('image', "Choose file...", ['class' => "custom-file-label"]) !!}
    </div>
</div>

@if (Config::get('lorekeeper.settings.masterlist_image_automation') === 1)
    <div class="form-group">
        {!! Form::checkbox('use_cropper', 1, 1, ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'id' => 'useCropper']) !!}
        {!! Form::label('use_cropper', 'Use Thumbnail Automation', ['class' => 'form-check-label ml-3']) !!} {!! add_help('A thumbnail is required for the upload (used for the masterlist). You can use the Thumbnail Automation, or upload a custom thumbnail.') !!}
    </div>
    <div class="card mb-3" id="thumbnailCrop">
        <div class="card-body">
            <div id="cropSelect">By using this function, the thumbnail will be automatically generated from the full image.</div>
            {!! Form::hidden('x0', 1) !!}
            {!! Form::hidden('x1', 1) !!}
            {!! Form::hidden('y0', 1) !!}
            {!! Form::hidden('y1', 1) !!}
        </div>
    </div>
@else
    <div class="form-group">
        {!! Form::checkbox('use_cropper', 1, 1, ['class' => 'form-check-input', 'data-toggle' => 'toggle', 'id' => 'useCropper']) !!}
        {!! Form::label('use_cropper', 'Use Image Cropper', ['class' => 'form-check-label ml-3']) !!} {!! add_help('A thumbnail is required for the upload (used for the masterlist). You can use the image cropper (crop dimensions can be adjusted in the site code), or upload a custom thumbnail.') !!}
    </div>
    <div class="card mb-3" id="thumbnailCrop">
        <div class="card-body">
            <div id="cropSelect">Select an image to use the thumbnail cropper.</div>
            <img src="#" id="cropper" class="hide" />
            {!! Form::hidden('x0', null, ['id' => 'cropX0']) !!}
            {!! Form::hidden('x1', null, ['id' => 'cropX1']) !!}
            {!! Form::hidden('y0', null, ['id' => 'cropY0']) !!}
            {!! Form::hidden('y1', null, ['id' => 'cropY1']) !!}
        </div>
    </div>
@endif
<div class="card mb-3" id="thumbnailUpload">
    <div class="card-body">
        {!! Form::label('Thumbnail Image') !!} {!! add_help('This image is shown on the masterlist page.') !!}
        <div>{!! Form::file('thumbnail') !!}</div>
        <div class="text-muted">Recommended size: {{ Config::get('lorekeeper.settings.masterlist_thumbnails.width') }}px x {{ Config::get('lorekeeper.settings.masterlist_thumbnails.height') }}px</div>
    </div>
</div>
<p class="alert alert-info">
    This section is for crediting the image creators. The first box is for the designer or artist's on-site username (if any). The second is for a link to the designer or artist if they don't have an account on the site.
</p>
<div class="form-group">
    {!! Form::label('Designer(s)') !!}
    <div id="designerList">
        <div class="mb-2 d-flex">
            {!! Form::select('designer_id[]', $userOptions, null, ['class'=> 'form-control mr-2 selectize', 'placeholder' => 'Select a Designer']) !!}
            {!! Form::text('designer_url[]', null, ['class' => 'form-control mr-2', 'placeholder' => 'Designer URL']) !!}
            <a href="#" class="add-designer btn btn-link" data-toggle="tooltip" title="Add another designer">+</a>
        </div>
    </div>
</div>
<div class="form-group">
    {!! Form::label('Artist(s)') !!}
    <div id="artistList">
        <div class="mb-2 d-flex">
            {!! Form::select('artist_id[]', $userOptions, null, ['class'=> 'form-control mr-2 selectize', 'placeholder' => 'Select an Artist']) !!}
            {!! Form::text('artist_url[]', null, ['class' => 'form-control mr-2', 'placeholder' => 'Artist URL']) !!}
            <a href="#" class="add-artist btn btn-link" data-toggle="tooltip" title="Add another artist">+</a>
        </div>
    </div>
</div>
<hr>

@if($lineageDetected)
    <p><strong>Character Genetic Data</strong> has detected that you might have a lineage extension installed. Do you want to try and automatically link the parents to their generated offspring?</p>
    <div class="form-group">
        {!! Form::checkbox('generate_lineage', 1, false, ['class' => 'form-check-input', 'data-toggle' => 'toggle']) !!}
        {!! Form::label('generate_lineage', 'Lineage Connection', ['class' => 'form-check-label ml-3']) !!}
    </div>
@endif

<div class="text-right">
    {!! Form::submit("Roll Litter!", ['class' => "btn btn-primary"]) !!}
</div>

{!! Form::close() !!}

<div class="designer-row hide mb-2">
    {!! Form::select('designer_id[]', $userOptions, null, ['class'=> 'form-control mr-2 designer-select', 'placeholder' => 'Select a Designer']) !!}
    {!! Form::text('designer_url[]', null, ['class' => 'form-control mr-2', 'placeholder' => 'Designer URL']) !!}
    <a href="#" class="add-designer btn btn-link" data-toggle="tooltip" title="Add another designer">+</a>
</div>
<div class="artist-row hide mb-2">
    {!! Form::select('artist_id[]', $userOptions, null, ['class'=> 'form-control mr-2 artist-select', 'placeholder' => 'Select an Artist']) !!}
    {!! Form::text('artist_url[]', null, ['class' => 'form-control mr-2', 'placeholder' => 'Artist URL']) !!}
    <a href="#" class="add-artist btn btn-link mb-2" data-toggle="tooltip" title="Add another artist">+</a>
</div>

@endsection

@section('scripts')
@parent
@include('widgets._character_create_options_js')
@include('widgets._image_upload_js')
<script>
    $(document).ready(function() {
        $('.parent-select').selectize();
        $('.parent-select').change(function(e) {
            var id = $(this).val();
            var genomes = $(this).parent().parent().find('.genomes');
            if (id < 1) {
                genomes.html("");
                return;
            }
            makeRequest("{{ url('admin/genetics/fetch-genomes') }}?id="+ id, genomes);
        });

        $('.preview-breeding').click(function(e) {
            e.preventDefault();
            var paramaters = "sire="+$("#father").val()+"&dam="+$("#mother").val();
            paramaters += "&min="+$("#size_min").val()+"&max="+$("#size_max").val();
            paramaters += "&twin="+$("#twin_chance").val()+"&depth="+$("#twin_depth").val();
            paramaters += "&chimera="+$("#chimera_chance").val()+"&genomes="+$("#chimera_depth").val();
            paramaters += "&limit="+$("#litter_limit").val();
            makeRequest("{{ url('admin/genetics/preview-breeding') }}?"+paramaters, $('.child-genomes'));
        });

        $('#species').change(function(e){
            makeRequest("{{ url('admin/masterlist/check-subtype') }}?species="+$(this).val()+"&myo=true", $("#subtypes"));
        });

        function makeRequest(url, element) {
            $.ajax({
                type: "GET", url: url, dataType: "text"
            }).done(function(res) {
                element.html(res);
                element.find('[data-toggle="tooltip"]').tooltip();
            }).fail(function (jqXHR, textStatus, errorThrown) {
                element.html("");
                alert("AJAX call failed: " + textStatus + ", " + errorThrown);
            });
        }
    });
</script>
@endsection
